dist: xenial
sudo: false
language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - gcc-4.8
      - unixodbc-dev
install:
  - pip install pycodestyle
before_script:
  - pip install coveralls
  - npm install
script:
  - pycodestyle prereq_map/ --exclude=migrations,prereq_map/static
  - ./node_modules/.bin/stylelint '**/*.vue' '**/*.css' '**/*.scss'
  - ./node_modules/.bin/eslint --ext .js,.vue prereq_map/static/prereq_map/js/components/
  - ./node_modules/.bin/eslint --ext .js,.vue prereq_map/static/prereq_map/js/pages/
  - coverage run --source=prereq_map/ --omit=prereq_map/migrations/* manage.py test prereq_map
after_success:
  - coveralls
